# Site settings
title: HKUST XRVislab
description: > # this means to ignore newlines until "baseurl:"
   I am a Ph.D. candidate at the Hong Kong University of Science and Technology (HKUST). I work on augmented reality, virtual reality, human-computer interaction, and data visualization.
domain: wtong2017.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://wtong2017.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /xrvislab-homepage-dev/      # place folder name if the site is served in a subfolder
production_url: "https://yuanlinping.github.io"
permalink: /blog/:year/:month/:title.html

# find me
email: lyuanaa@connect.ust.hk
github_username: yuanlinping
github_url: https://github.com/yuanlinping
google_scholar_url: https://scholar.google.com/citations?user=xp3QhPkAAAAJ&hl=en



sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
